[package]
name = "intro"
version = "0.1.0"
authors = ["SamPeng <dev.sampeng@gmail.com>"]

[dependencies]
log = "0.3"
regex = "0.2.1"
crossbeam = "0.2"
chrono = "0.3"
time = "0.1"


[dev-dependencies]


[[bench]]
name = "print"
harness = false
