[package]
name = "intro"
version = "0.1.0"
authors = ["SamPeng <dev.sampeng@gmail.com>"]

[dependencies]
log = "0.3"
regex = "0.2.1"
bencher = "0.1.2"
env_logger = "0.3"
mio = "0.6"

[dev-dependencies]


[[bench]]
name = "print"
harness = false
